---
title: "TR2"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r cars}
library(readr)
library(ggplot2)
library(dplyr)
```

```{r}
Bfile<-read.csv("fullmatrix.csv")
head(Bfile)

B<-as.matrix(Bfile[1:429,4:9])
btb<-t(B)%*%B
btb
eigen(btb)
```

```{r}
u1<-svd(btb)$u[,1]/norm(svd(btb)$u[,1],'2') #normalized dominate eigenvector
u2<-svd(btb)$u[,2]/norm(svd(btb)$u[,2], '2') #normalized second eigenvector
btbval <- svd(btb)$d
head(u1)

```

```{r}
btbval/sum(btbval)
```
```{r}
bbt <- B %*% t(B)
v1 <- eigen(bbt)$vectors[,1]/norm(eigen(bbt)$vectors[,1],'2') #normalized v1
v2 <- eigen(bbt)$vectors[,2]/norm(eigen(bbt)$vectors[,2],'2') #normalized v2

marijuana <- data.frame(
  party = Bfile[1:429,3],
  v1 = v1,
  v2 = v2
)

ggplot() + 
  geom_jitter(data = marijuana, aes(x = v1, y = v2, color = party),size=2,height=.005,width=.005) +
  scale_color_manual(values = c("Democrat" = "blue", "Republican" = "red"))

```

In this case, we found that the dominant eigenvector accounts for over 78% of the voting matrix, the second vector account for over 13% of the voting matrix, along with the other eigenvectors that account for less than 5% of the matrix.

We can use the dominant and the second eigenvectors to approximate our voting matrix, which gives us:
```{r}
appro <- sqrt(eigen(btb)$values[1]) * u1 %*% t(v1) + sqrt(eigen(btb)$values[2]) * u2 %*% t(v2)
appro
```



```{r}

Bfile<-read.csv("fullmatrix.csv")
head(Bfile)

B<-as.matrix(Bfile[1:429,10:24])
btb<-t(B)%*%B
btb
eigen(btb)

u1<-svd(btb)$u[,1]/norm(svd(btb)$u[,1],'2') #normalized dominate eigenvector
u2<-svd(btb)$u[,2]/norm(svd(btb)$u[,2],'2') #normalized second eigenvector
btbval <- svd(btb)$d
head(u1)


btbval/sum(btbval)

bbt <- B %*% t(B)
b1 <- eigen(bbt)$vectors[,1]/norm(eigen(bbt)$vectors[,1],'2') #normalized v1
b2 <- eigen(bbt)$vectors[,2]/norm(eigen(bbt)$vectors[,2],'2') #normalized v2
b3 <- eigen(bbt)$vectors[,3]/norm(eigen(bbt)$vectors[,3],'2') #normalized v3
controversial <- data.frame(
  party = Bfile[1:429,3],
  v1 = b1,
  v2 = b2,
  v3 = b3
)

ggplot(controversial,aes(v1,v2)) + 
  geom_jitter(aes(color = party),size=2,width=.005,height=.005) +
  scale_color_manual(values = c("Democrat" = "blue", "Republican" = "red"))

appro <- sqrt(eigen(btb)$values[1]) * u1 %*% t(v1) + sqrt(eigen(btb)$values[2]) * u2 %*% t(v2)
appro
```
##kmeans baby
```{r}
controversial_k<-controversial%>% 
  select(v1,v2,v3)
set.seed(169)
kclust_controversial<-kmeans(scale(controversial_k),centers=3)
kclust_controversial2<-kmeans(controversial_k,centers=3)
head(kclust_controversial)
head(kclust_controversial2)

controversial<-controversial%>%
  mutate(kclust_controversial=as.factor(as.numeric(kclust_controversial$cluster)))
ggplot(controversial,aes(v1,v2)) + 
  geom_jitter(aes(color = kclust_controversial),size=1,width=.005,height=.005) 
controversial$v3
```
##heirarchical clustering 
```{r}
dist_mat_scaled<-dist(scale(controversial_k))
hc_complete<-hclust(dist_mat_scaled,method="complete")
plot(hc_complete)
controversial<-controversial%>%
  mutate(hclust_height3=factor(cutree(hc_complete,h=2.5)))
ggplot(controversial,aes(v1,v2)) + 
  geom_jitter(aes(color = hclust_height3),size=1,width=.005,height=.005)
```

```{r}

Bfile<-read.csv("fullmatrix.csv")
head(Bfile)

B<-as.matrix(Bfile[1:429,4:24])
btb<-t(B)%*%B
btb
eigen(btb)

u1<-svd(btb)$u[,1]/norm(svd(btb)$u[,1],'2') #normalized dominate eigenvector
u2<-svd(btb)$u[,2]/norm(svd(btb)$u[,2],'2') #normalized second eigenvector
btbval <- svd(btb)$d
head(u1)


btbval/sum(btbval)

bbt <- B %*% t(B)
v1 <- eigen(bbt)$vectors[,1]/norm(eigen(bbt)$vectors[,1],'2') #normalized v1
v1
v2 <- eigen(bbt)$vectors[,2]/norm(eigen(bbt)$vectors[,2],'2') #normalized v2

controversial <- data.frame(
  party = Bfile[1:429,3],
  name = Bfile[1:429,2],
  v1 = v1,
  v2 = v2
)
controversial

ggplot() + 
  geom_jitter(data = controversial, aes(x = v1, y = v2, color = party,label=controversial$name),size=2,width=.005,height=.005) +
  geom_text()+
  scale_color_manual(values = c("Democrat" = "blue", "Republican" = "red"))


appro <- sqrt(eigen(btb)$values[1]) * u1 %*% t(v1) + sqrt(eigen(btb)$values[2]) * u2 %*% t(v2)
appro
```









